### ISSUE TITLE
Bigquery Query - Can not use DECLARE when a destinationTable is provided

### ISSUE THREAD

**Issue by Skraye** [kestra-io/plugin-gcp#194]
### Expected Behavior

When I use DECLARE to implement some functions or variables for my query, I want it to work with my query that will fill my table.

### Actual Behaviour

Instead, it tells me that I cannot set destination table with Scripts
![image](https://user-images.githubusercontent.com/37600690/202133882-c57f2957-da1e-4cc6-bb27-7eacafa86551.png)

### Steps To Reproduce

1. Create a bigquery.query task
2. Use a DECLARE statement in the query
3. Execute your flow

### Environment Information

- Kestra Version: 0.5.2
- Plugin version: 0.5.0

### Example flow

 - id: my_id
    type: com.leroymerlin.dataplatform.gcp.bigquery.Query
    destinationTable: project.dataset.table
    sql: |
      DECLARE X int64;
      set X=3;
      Select X

**Comment by tchiotludo** [comment]
Expected behaviour, 
You are using [BigQuery Scripting](https://cloud.google.com/bigquery/docs/reference/standard-sql/procedural-language), as soon as you are using this, you can't use `destinationTable` any more and you should do instead `INSERT INTO tableA SELECT * FROM tableB`
