### ISSUE TITLE
BigTable

### ISSUE THREAD

**Issue by loicmathieu** [kestra-io/plugin-gcp#216]
### Feature description

BigTable

**Comment by anna-geller** [comment]
Deprioritized for now, we can reopen in the future if there's interest from the community.

**Comment by suraj-0628** [comment]
Hey , @fdelbrayelle I would like to work on this issue .

**Comment by fdelbrayelle** [comment]
Allright go ahead @suraj-0628 thanks 🚀

**Comment by MilosPaunovic** [comment]
Hey @suraj-0628, are there any updates on this?

**Comment by suraj-0628** [comment]
Hi @MilosPaunovic , Just now raised a PR .
