### ISSUE TITLE
use AbstractTask for gcloud cli plugin

### ISSUE THREAD

**Issue by bcrawford18** [kestra-io/plugin-gcp#288]
### Feature description

Could we remove the requirement for the service Account key and extend AbstractTask vs Task for authorizing for gcloud cli plugin? This way the gcloud plugin will authenticate the same way as the other plugins.

**Comment by tchiotludo** [comment]
In fact, it was already [handle in the code](https://github.com/kestra-io/plugin-gcp/blob/cfbcaabcc3745075494647b8e8cd3d163135dcdf/src/main/java/io/kestra/plugin/gcp/cli/GCloudCLI.java#L139) but enforce on the properties (with no reason), fix in https://github.com/kestra-io/plugin-gcp/commit/cfbcaabcc3745075494647b8e8cd3d163135dcdf

**Comment by bcrawford18** [comment]
Thank you! I was trying to get around having to use it! Thanks

**Comment by tchiotludo** [comment]
This plugin is new, it will be helpful for us if you want to share why your are using this one on our [slack](https://kestra.io/slack)
