### ISSUE TITLE
Task to create a Google Batch Job

### ISSUE THREAD

**Issue by loicmathieu** [kestra-io/plugin-gcp#365]
### Feature description

Based on the existing work done for the Google Batch task runner.

**Comment by anna-geller** [comment]
We've discussed that we'll avoid the same functionality as a task runner and task. The preference long-term is to deprecate:
- K8s PodCreate task (in favor of KubernetesTaskRunner)
- VertexAI task (in favor of VertexAITaskRunner)

to have one holistic UX for all script/container tasks
