### ISSUE TITLE
Task to create a Google CloudRun Job

### ISSUE THREAD

**Issue by loicmathieu** [kestra-io/plugin-gcp#373]
### Feature description

Based on the implementation of the CloudRun task runner.

**Comment by anna-geller** [comment]
Can you say why it is beneficial to have it as a task? 

I feel like if we add it also as a task, we'll be getting support questions:
"When should I use that task vs a task runner?"

so if this doesn't add substantial benefit, better if we have one way to interact with CloudRun (for simplicity) 👍

**Comment by loicmathieu** [comment]
For the same reason we have a PodCreate and a Docker.Run task, it is a straightforward plugin to launch a CloudRun Job that is not necessary a script (for ex: with an interpreter that is not a shell, or even a container with predefined entrypoint and commands ...).

As it's not hard to build one based on the TaskRunner, it could be good to have it (like we plan to add one for AWS Batch, Azure Batch and Google Batch).

**Comment by anna-geller** [comment]
perfect, thx for the extra context, the interpreter is a good reason. Let's keep the issue open, we can prioritize this higher when we see demand from the community

**Comment by anna-geller** [comment]
discussed with Ludo, the intended behavior is to avoid having a task and taskRunner that do the same
