### ISSUE TITLE
GCP Batch Task Runner does not retry DEADLINE_EXCEEDED but instead Fails

### ISSUE THREAD

**Issue by japerry911** [kestra-io/plugin-gcp#418]
I am convinced that this error below comes from Batch Task Runner receiving an error, DEADLINE_EXCEEDED, and not retrying on the API endpoint for GetJob (seeing one error at the same time this came up in the API page in GCP - see image).

![image](https://github.com/kestra-io/kestra/assets/21957238/e2122f14-b4e0-425c-b846-2c4f34332e28)

```
2024-07-03 03:07:54.883io.grpc.StatusRuntimeException: DEADLINE_EXCEEDED: deadline exceeded after 59.999868834s. Name resolution delay 0.000000000 seconds. [closed=[], open=[[remote_addr=batch.googleapis.com/<ip>:443]]]
```

```
2024-07-03 03:07:54.883DEADLINE_EXCEEDED: deadline exceeded after 59.999868834s. Name resolution delay 0.000000000 seconds. [closed=[], open=[[remote_addr=batch.googleapis.com/<ip>:443]]]
```

Is it possible to check if there are retries for Task Runner when it is polling, and if there are, that DEADLINE_EXCEEDED is retried?

This is the first time this has happened (but it happened on one of our long jobs at the very end), I figured it would be easy patch to prevent it from happening again.

Let me know if you need anymore detail, thank you team.

### Environment

- Kestra Version: 0.17.8
- Operating System (OS/Docker/Kubernetes): Kestra Cloud

**Comment by loicmathieu** [comment]
Hi @japerry911 I implemented a simple retry (3x, separated by 10s).
I'm preparing a backport for 0.17 so it will be in the next release.

**Comment by japerry911** [comment]
Thank you @loicmathieu , that's perfect! We really appreciate it 🚀
