### ISSUE TITLE
Spanner

### ISSUE THREAD

**Issue by tchiotludo** [kestra-io/plugin-gcp#86]
https://cloud.google.com/spanner

**Comment by anna-geller** [comment]
already included in the wishlist :) https://www.notion.so/kestra-io/Plugin-Backlog-71573110f3ee4890afc99095aa19e7d1?pvs=4

**Comment by suraj-0628** [comment]
Hey @fdelbrayelle 👋 , I would like to work on this feature.

**Comment by fdelbrayelle** [comment]
Hi @suraj-0628 :wave: Allright, thanks!
